[project]
name = "era-proxy"
authors = []
description = ""
telemetry = false
requirements = []
[contracts.era-access-control]
path = "contracts/era-access-control.clar"
depends_on = []

[contracts.era-events-log]
path = "contracts/era-events-log.clar"
depends_on = []

[contracts.era-token-bridge]
path = "contracts/era-token-bridge.clar"
depends_on = []

[contracts.era-token-vault]
path = "contracts/era-token-vault.clar"
depends_on = []

[contracts.era-cross-chain-sync]
path = "contracts/era-cross-chain-sync.clar"
depends_on = []

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
